### ISSUE TITLE
Submit SQL stream task through REST api failed

### ISSUE THREAD

**Issue by 22221cjp** [ververica/flink-sql-gateway#17]
Through the rest api "http://127.0.0.1:8083/v1/sessions/ "+ sessionId +"/statements"  to submit stream task failed.

submit sql stream task to sql-gateway failed through rest api "http://127.0.0.1:8083/v1/sessions/ "+ sessionId +"/statements"

Steps:

1. Create the session through api http://127.0.0.1:8083/v1/sessions

The request body is: 

	{
	    "session_name": "test_session",
	    "planner": "blink", 
	    "execution_type": "streaming"
	}

2. Through api "http://127.0.0.1:8083/v1/sessions/ "+ sessionId +"/statements" request execution statement.
The statement is:

CREATE TABLE trade_datasource (
	userId VARCHAR,
    itemId VARCHAR,
    categoryId VARCHAR,
    behavior VARCHAR,
    `timestamp` BIGINT
) WITH (
    'connector.type' = 'kafka',  
    'connector.version' = 'universal',  
    'connector.topic' = 'user_trade',  
    'connector.startup-mode' = 'earliest-offset',  
    'connector.properties.zookeeper.connect' = 'localhost:2181',  
    'connector.properties.bootstrap.servers' = 'localhost:9092',  
    'format.type' = 'json'
);

CREATE TABLE pvuv_sink (
    user_id VARCHAR,
    item_id VARCHAR,
    category_id VARCHAR,
    behavior VARCHAR,
    `ts` BIGINT
) WITH (
'connector.type' = 'jdbc',
'connector.url' = 'jdbc:mysql://127.0.0.1:3306/flink_sql_platform',
'connector.table' = 'pvuv_sink',
'connector.username' = 'root',
'connector.password' = '123456',
'connector.write.flush.max-rows' = '1'
);

INSERT INTO pvuv_sink 
SELECT
userId as user_id,
itemId as item_id,
categoryId as category_id,
behavior,
`timestamp` as ts
FROM trade_datasource where behavior = 'pv';

These three statements are executed correctly in Flink SQL client embedded. Execute one SQL at a time, with three requests. The response to the request is as follows. What is the problem?

{"statement":"CREATE TABLE trade_datasource (\n\tuserId VARCHAR,\n    itemId VARCHAR,\n    categoryId VARCHAR,\n    behavior VARCHAR,\n    `timestamp` BIGINT\n) WITH (\n    'connector.type' = 'kafka',  \n    'connector.version' = 'universal',  \n    'connector.topic' = 'user_trade',  \n    'connector.startup-mode' = 'earliest-offset',  \n    'connector.properties.zookeeper.connect' = 'localhost:2181',  \n    'connector.properties.bootstrap.servers' = 'localhost:9092',  \n    'format.type' = 'json'\n)"}

{"results":[{"columns":[{"name":"affected_row_count","type":"BIGINT NOT NULL"}],"data":[[0]]}],"statement_types":["CREATE_TABLE"]}

{"statement":"CREATE TABLE pvuv_sink (\n    user_id VARCHAR,\n    item_id VARCHAR,\n    category_id VARCHAR,\n    behavior VARCHAR,\n    `ts` BIGINT\n) WITH (\n'connector.type' = 'jdbc',\n'connector.url' = 'jdbc:mysql://127.0.0.1:3306/flink_sql_platform',\n'connector.table' = 'pvuv_sink',\n'connector.username' = 'root',\n'connector.password' = '123456',\n'connector.write.flush.max-rows' = '1'\n)"}

{"results":[{"columns":[{"name":"affected_row_count","type":"BIGINT NOT NULL"}],"data":[[0]]}],"statement_types":["CREATE_TABLE"]}

{"statement":"INSERT INTO pvuv_sink \nSELECT\nuserId as user_id,\nitemId as item_id,\ncategoryId as category_id,\nbehavior,\n`timestamp` as ts\nFROM trade_datasource where behavior = 'pv'"}

{"errors":["Internal server error.","<Exception on server side:\ncom.ververica.flink.table.gateway.SqlExecutionException: Invalid SQL update statement.\n\tat com.ververica.flink.table.gateway.operation.InsertOperation.executeUpdateInternal(InsertOperation.java:157)\n\tat com.ververica.flink.table.gateway.operation.InsertOperation.execute(InsertOperation.java:80)\n\tat com.ververica.flink.table.gateway.Session.runStatement(Session.java:95)\n\tat com.ververica.flink.table.gateway.rest.handler.StatementExecuteHandler.handleRequest(StatementExecuteHandler.java:81)\n\tat com.ververica.flink.table.gateway.rest.handler.AbstractRestHandler.respondToRequest(AbstractRestHandler.java:77)\n\tat com.ververica.flink.table.gateway.rest.handler.AbstractHandler.channelRead0(AbstractHandler.java:178)\n\tat com.ververica.flink.table.gateway.rest.handler.AbstractHandler.channelRead0(AbstractHandler.java:75)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat org.apache.flink.runtime.rest.handler.router.RouterHandler.routed(RouterHandler.java:110)\n\tat org.apache.flink.runtime.rest.handler.router.RouterHandler.channelRead0(RouterHandler.java:89)\n\tat org.apache.flink.runtime.rest.handler.router.RouterHandler.channelRead0(RouterHandler.java:54)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat org.apache.flink.shaded.netty4.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat org.apache.flink.runtime.rest.FileUploadHandler.channelRead0(FileUploadHandler.java:174)\n\tat org.apache.flink.runtime.rest.FileUploadHandler.channelRead0(FileUploadHandler.java:68)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)\n\tat org.apache.flink.shaded.netty4.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)\n\tat org.apache.flink.shaded.netty4.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)\n\tat org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)\n\tat org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)\n\tat org.apache.flink.shaded.netty4.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.flink.table.api.TableException: findAndCreateTableSource failed.\n\tat org.apache.flink.table.factories.TableFactoryUtil.findAndCreateTableSource(TableFactoryUtil.java:55)\n\tat org.apache.flink.table.factories.TableFactoryUtil.findAndCreateTableSource(TableFactoryUtil.java:92)\n\tat org.apache.flink.table.planner.plan.schema.CatalogSourceTable.findAndCreateTableSource(CatalogSourceTable.scala:156)\n\tat org.apache.flink.table.planner.plan.schema.CatalogSourceTable.tableSource$lzycompute(CatalogSourceTable.scala:65)\n\tat org.apache.flink.table.planner.plan.schema.CatalogSourceTable.tableSource(CatalogSourceTable.scala:65)\n\tat org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.scala:76)\n\tat org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3328)\n\tat org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2357)\n\tat org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2051)\n\tat org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2005)\n\tat org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:646)\n\tat org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:627)\n\tat org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3181)\n\tat org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:563)\n\tat org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:148)\n\tat org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:135)\n\tat org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:522)\n\tat org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:436)\n\tat org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:154)\n\tat org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlInsert(SqlToOperationConverter.java:342)\n\tat org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:142)\n\tat org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:66)\n\tat org.apache.flink.table.api.internal.TableEnvironmentImpl.sqlUpdate(TableEnvironmentImpl.java:484)\n\tat org.apache.flink.table.api.java.internal.StreamTableEnvironmentImpl.sqlUpdate(StreamTableEnvironmentImpl.java:331)\n\tat com.ververica.flink.table.gateway.operation.InsertOperation.lambda$executeUpdateInternal$1(InsertOperation.java:148)\n\tat com.ververica.flink.table.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:230)\n\tat com.ververica.flink.table.gateway.operation.InsertOperation.executeUpdateInternal(InsertOperation.java:145)\n\t... 46 more\nCaused by: org.apache.flink.table.api.NoMatchingTableFactoryException: Could not find a suitable table factory for 'org.apache.flink.table.factories.TableSourceFactory' in\nthe classpath.\n\nReason: Required context properties mismatch.\n\nThe following properties are requested:\nconnector.properties.bootstrap.servers=localhost:9092\nconnector.properties.zookeeper.connect=localhost:2181\nconnector.startup-mode=earliest-offset\nconnector.topic=user_trade\nconnector.type=kafka\nconnector.version=universal\nformat.type=json\nschema.0.data-type=VARCHAR(2147483647)\nschema.0.name=userId\nschema.1.data-type=VARCHAR(2147483647)\nschema.1.name=itemId\nschema.2.data-type=VARCHAR(2147483647)\nschema.2.name=categoryId\nschema.3.data-type=VARCHAR(2147483647)\nschema.3.name=behavior\nschema.4.data-type=BIGINT\nschema.4.name=timestamp\n\nThe following factories have been considered:\norg.apache.flink.table.sources.CsvBatchTableSourceFactory\norg.apache.flink.table.sources.CsvAppendTableSourceFactory\n\tat org.apache.flink.table.factories.TableFactoryService.filterByContext(TableFactoryService.java:322)\n\tat org.apache.flink.table.factories.TableFactoryService.filter(TableFactoryService.java:190)\n\tat org.apache.flink.table.factories.TableFactoryService.findSingleInternal(TableFactoryService.java:143)\n\tat org.apache.flink.table.factories.TableFactoryService.find(TableFactoryService.java:96)\n\tat org.apache.flink.table.factories.TableFactoryUtil.findAndCreateTableSource(TableFactoryUtil.java:52)\n\t... 72 more\n\nEnd of exception on server side>"]}

**Comment by godfreyhe** [comment]
the root cause is `Caused by: org.apache.flink.table.api.NoMatchingTableFactoryException: Could not find a suitable table factory for 'org.apache.flink.table.factories.TableSourceFactory' in
the classpath.`. you should add the related collector jars into `flink/lib` or start gateway with `--jar`

**Comment by 22221cjp** [comment]
That's the reason. Has been solved, thank you：）
