### ISSUE TITLE
How to recover job in new session?

### ISSUE THREAD

**Issue by wooplevip** [ververica/flink-sql-gateway#27]
From README
>Flink SQL gateway stores the session properties in memory now. If the service is stopped or crashed, all properties are lost.

Do you have any workaround or suggestions for this case to get previous running job's status or cancel it ? Thanks in advance.

**Comment by godfreyhe** [comment]
we plan to support store session properties into external storage, when sql gateway crashes or restarts, client can also get status or cancel through session id and job id.

**Comment by wooplevip** [comment]
OK, thanks.
