### ISSUE TITLE
Support CREATE CATALOG

### ISSUE THREAD

**Issue by fpompermaier** [ververica/flink-sql-gateway#33]
This is super useful but is supported only in Flink >= 1.11

**Comment by godfreyhe** [comment]
you have a dev branch: https://github.com/ververica/flink-sql-gateway/tree/flink_1.11_SNAPSHOT
we can add "CREATE CATALOG" in dev branch first

**Comment by fpompermaier** [comment]
Yes I'm working on that. I can try to implement it in order to get confident with the project. Could you please give me some advice on how to proceed on this?

**Comment by godfreyhe** [comment]
it's easy to support this, first let `SqlCommandParser` support CREARE_CATALOG command (refer to SqlCommand.CREATE_DATABASE), then update OperationFactory#createOperation method

**Comment by fpompermaier** [comment]
Ok thanks, I'll try to implement it!

**Comment by fpompermaier** [comment]
I've implemented this functionality quite easily. Test are quite hard to understand..which and how many tests should I add? Can you please help me here?

**Comment by godfreyhe** [comment]
add some tests in `SqlCommandParserTest` and `DDLOperationTest`. There is a test catalog named `SimpleCatalogFactory`, you can use that.
