### ISSUE TITLE
Add Postgres tests

### ISSUE THREAD

**Issue by fpompermaier** [ververica/flink-sql-gateway#37]
Investigate why this statement works 

```sql
SELECT * FROM `mypg`.`postgres`.`public.link` 
```
but this does not:
```sql
DESCRIBE `mypg`.`postgres`.`public.link` 
```

**Comment by godfreyhe** [comment]
@fpompermaier thanks for reporting this, we had fix the bug, see https://github.com/ververica/flink-sql-gateway/pull/42
