### ISSUE TITLE
Master branch compile error with Flink 1.13

### ISSUE THREAD

**Issue by link3280** [ververica/flink-sql-gateway#84]
ca41046 Updates Flink version to 1.13 without adjustment to the interfaces changes in 1.13, so the master branch doesn't compile.

**Comment by LinMingQiang** [comment]
> [ca41046](https://github.com/ververica/flink-sql-gateway/commit/ca4104681a8b4a0716204da090a27da9c814fd40) Updates Flink version to 1.13 without adjustment to the interfaces changes in 1.13, so the master branch doesn't compile.

Afraid so
